// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdYv7XJwu0J6AXfOY7B1-kBDtEbHSThtI',
    appId: '1:929317894873:web:dfd7247885912689e99cc8',
    messagingSenderId: '929317894873',
    projectId: 'spotmancing-pab2',
    authDomain: 'spotmancing-pab2.firebaseapp.com',
    databaseURL: 'https://spotmancing-pab2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spotmancing-pab2.firebasestorage.app',
    measurementId: 'G-WQWPK7V2WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEOC24i4H_r5AAsl4W68aGpmNGR4mioXA',
    appId: '1:929317894873:android:1b907e161161aebce99cc8',
    messagingSenderId: '929317894873',
    projectId: 'spotmancing-pab2',
    databaseURL: 'https://spotmancing-pab2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spotmancing-pab2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWwH_VoYBJ5zcP-B6Vz_moYEssphADHl4',
    appId: '1:929317894873:ios:23f5d0752c955954e99cc8',
    messagingSenderId: '929317894873',
    projectId: 'spotmancing-pab2',
    databaseURL: 'https://spotmancing-pab2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spotmancing-pab2.firebasestorage.app',
    iosBundleId: 'com.example.spotmancingPab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWwH_VoYBJ5zcP-B6Vz_moYEssphADHl4',
    appId: '1:929317894873:ios:23f5d0752c955954e99cc8',
    messagingSenderId: '929317894873',
    projectId: 'spotmancing-pab2',
    databaseURL: 'https://spotmancing-pab2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spotmancing-pab2.firebasestorage.app',
    iosBundleId: 'com.example.spotmancingPab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdYv7XJwu0J6AXfOY7B1-kBDtEbHSThtI',
    appId: '1:929317894873:web:ce592fb84f4ed996e99cc8',
    messagingSenderId: '929317894873',
    projectId: 'spotmancing-pab2',
    authDomain: 'spotmancing-pab2.firebaseapp.com',
    databaseURL: 'https://spotmancing-pab2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spotmancing-pab2.firebasestorage.app',
    measurementId: 'G-3906KBPBJF',
  );

}